development:
  adapter: postgresql
  database: activeresume_development
  username: postgres
  password: solo4170
  
test: &test
  adapter: postgresql
  database: activeresume_test
  username: postgres
  password: solo4170

cucumber:
  <<: *test